### ISSUE TITLE
As a Jobseeker, I can unfollow  those companies/organizations.

### ISSUE THREAD

**Issue by sefinehtesfa34** [samiabat/Flutter-MobileApp-Job-Vacancy#14]
* As a Jobseeker, I can unfollow  those companies/organizations.

**Comment by YabTek** [comment]
As a jobseeker, I want to search for jobs, so that I can easily know where to apply.

**Comment by YabTek** [comment]
As a jobseeker, I want to see requirements for employment, so that I can be ready to apply.
